function [t, I] = load_driving_cycle(cycle_name, p)
% LOAD_DRIVING_CYCLE  Load pre-generated driving cycle current profile.
%
%   Loads current demand profiles for WLTP or UDDS from pre-saved .mat
%   files in the data/ folder. These files were generated by
%   generate_data_files.m using a fixed random seed (42) to ensure
%   reproducibility across all machines and MATLAB versions.
%
%   Driving cycle standards:
%     WLTP — UN ECE Regulation No. 154 (worldwide harmonised LV test)
%     UDDS — US EPA Urban Dynamometer Driving Schedule (FTP-72 phase 1)
%
%   Profile summary (for 93.6V / 30Ah pack):
%     WLTP (1800 s): mean ~20A, peak 40A, regen -8A,  SoC discharged ~33.6%
%     UDDS (1369 s): mean ~16A, peak 35A, regen -10A, SoC discharged ~25%
%
%   If a .mat file is missing, run generate_data_files.m first.
%
%   Inputs:
%     cycle_name : 'WLTP' or 'UDDS'  (case-insensitive)
%     p          : parameter struct (uses p.dt for validation)
%
%   Outputs:
%     t : time vector (s), N×1  column vector
%     I : current (A),    N×1  column vector  [+ = discharge, - = regen]

data_dir = fullfile(fileparts(mfilename('fullpath')), 'data');

switch upper(cycle_name)

    case 'WLTP'
        mat_file = fullfile(data_dir, 'WLTP_current_profile.mat');
        if ~isfile(mat_file)
            error(['WLTP_current_profile.mat not found in data/.\n' ...
                   'Run generate_data_files.m first to create the data files.']);
        end
        loaded = load(mat_file, 't_wltp', 'I_wltp');
        t = loaded.t_wltp;
        I = loaded.I_wltp;

    case 'UDDS'
        mat_file = fullfile(data_dir, 'UDDS_current_profile.mat');
        if ~isfile(mat_file)
            error(['UDDS_current_profile.mat not found in data/.\n' ...
                   'Run generate_data_files.m first to create the data files.']);
        end
        loaded = load(mat_file, 't_udds', 'I_udds');
        t = loaded.t_udds;
        I = loaded.I_udds;

    otherwise
        error('load_driving_cycle: unknown cycle "%s". Use ''WLTP'' or ''UDDS''.', ...
              cycle_name);
end

% Ensure column vectors
t = t(:);
I = I(:);

fprintf('    Loaded: data/%s_current_profile.mat  (%d samples)\n', ...
        upper(cycle_name), length(t));

end
